INSERT INTO quotes (genre, text) VALUES 
('motivation', 'Learning begins when you stop trying to look capable and allow yourself to be curious instead.'),
('motivation', 'Growth rarely announces itself; it happens quietly while you keep showing up.'),
('motivation', 'Progress is often invisible until you pause and look back.'),
('motivation', 'The most meaningful lessons arrive disguised as frustration.'),
('motivation', 'Learning is less about talent and more about sustained attention.'),
('motivation', 'Learning reshapes not just what you know, but how you notice the world.'),
('motivation', 'The questions you avoid often hold the lessons you need most.'),
('motivation', 'The depth of learning is measured by how much it changes your thinking.'),
('motivation', 'Growth often feels like standing still—until you notice how much has shifted.'),
('motivation', 'The depth of learning is revealed when you explain it simply.'),
('motivation', 'What you learn slowly stays with you longest.'),
('motivation', 'Learning is a practice, not a phase.'),
('motivation', 'Learning is not linear; it loops, deepens, and revisits old ground with new eyes.'),
('motivation', 'Knowledge deepens when it is questioned, not defended.'),
('motivation', 'Knowing something once is not the same as understanding it.'),
('motivation', 'The value of knowledge is revealed through use, not possession.'),
('motivation', 'You don''t need more confidence; you need more consistency.'),
('motivation', 'Progress is built by returning, especially on the days you don''t feel like it.'),
('motivation', 'Motivation fades—systems remain.'),
('motivation', 'The work doesn''t need to be perfect; it needs to continue.'),
('motivation', 'Small effort, repeated, changes direction.'),
('motivation', 'Discipline is choosing the long reward over the short escape.'),
('motivation', 'You are allowed to move slowly, but not to stop.'),
('motivation', 'What you practice daily becomes your direction.'),
('motivation', 'The days that feel unproductive often lay the groundwork.'),
('motivation', 'Showing up is already an act of courage.'),
('motivation', 'You build strength by doing things before you feel ready.'),
('motivation', 'The hardest part is often simply beginning again.'),
('motivation', 'Effort compounds even when results are delayed.'),
('motivation', 'You don''t rise to goals; you fall to habits.'),
('motivation', 'Consistency is self-respect in action.');
